/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.Conexion;
import Modelos.MCArticuloTipo;
import Modelos.MCCaracteristica;
import Modelos.ValidadorEntradas;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Bedoy
 */
public class NuevaMercancia extends javax.swing.JFrame {

    ArrayList<MCArticuloTipo> articulo_tipo;
    DefaultTableModel modelo = new DefaultTableModel();
    MCCaracteristica mcc;
    boolean mode_editor = false;
    public static NuevaMercancia mthis;
    /**
     * Creates new form NuevaMercancia
     */
    public NuevaMercancia() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.jTable1.setModel(modelo);
        this.modelo.setColumnIdentifiers(new Object[]{"Clave articulo", "Modelo", "Tipo"});
        consulta();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/logosmall.png"));
        setIconImage(icon);
        mthis = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sNota = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sCantidad = new javax.swing.JTextField();
        sArticulo = new javax.swing.JComboBox();
        sNumero = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logi.png"))); // NOI18N

        sNota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sNota.setText("NOTA:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("DATOS PREVIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(sNota)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sNota)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("NUMERO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("CANTIDAD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ARTICULO");

        sCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCantidadActionPerformed(evt);
            }
        });

        sArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sArticulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sArticuloActionPerformed(evt);
            }
        });

        sNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.0", "3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0", "9.5", "10.0" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("RELACION DE ARTICULOS");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sCantidad)
                            .addComponent(sNumero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(sArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 153));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("OPCIONES");

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("SALIR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sArticuloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String validarCantidad = ValidadorEntradas.validarCantidad(this.sCantidad.getText());
        if (!validarCantidad.equals("OK")) {
            JOptionPane.showMessageDialog(this, validarCantidad);
        } else {

            if (mode_editor) {
                try {
                    // TODO add your handling code here:

                    /* new Conexion().getSt().execute("update caracteristicas "
                     + "set numero = "+this.sNumero+", "
                     + "set cantidad= "+this.sCantidad+", "
                     + "set Articulo_idArticulo =" + this.articulo_tipo.get(this.sArticulo.getSelectedIndex()).getId() + ""
                     + ") ");
                     */
                    System.out.println("update caracteristicas "
                            + "set numero = " + this.sNumero.getSelectedItem() + ", "
                            + " cantidad= " + this.sCantidad.getText() + ", "
                            + " Articulo_idArticulo =" + this.articulo_tipo.get(this.sArticulo.getSelectedIndex()).getId() + " "
                            + "where idCaracteristicas =  " + this.mcc.getId());
                    JOptionPane.showMessageDialog(null, "Modificacion exitosa", "", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            } else {
                try {
                    // TODO add your handling code here:
                    int idCaracteristica = -1;
                    System.out.println(""
                            + "select idCaracteristicas "
                            + "from caracteristicas "
                            + "where Articulo_idArticulo = " + this.articulo_tipo.get(this.sArticulo.getSelectedIndex()).getId() + " "
                            + "and "
                            + "numero = " + Integer.parseInt(this.sCantidad.getText()) + "");
                    ResultSet rs = new Conexion().getSt().executeQuery(""
                            + "select idCaracteristicas "
                            + "from caracteristicas "
                            + "where Articulo_idArticulo = " + this.articulo_tipo.get(this.sArticulo.getSelectedIndex()).getId() + " "
                            + "and "
                            + "numero = " + Float.parseFloat(this.sNumero.getSelectedItem().toString()) + "");
                    while (rs.next()) {
                        idCaracteristica = rs.getInt(1);
                    }
                    if (idCaracteristica == -1) {
                        new Conexion().getSt().execute("insert into caracteristicas values("
                                + "null, "
                                + "" + Float.parseFloat(this.sNumero.getSelectedItem().toString()) + ", "
                                + "" + Integer.parseInt(this.sCantidad.getText()) + ", "
                                + "" + this.articulo_tipo.get(this.sArticulo.getSelectedIndex()).getId() + ""
                                + ") ");
                        JOptionPane.showMessageDialog(null, "Carga exitosa", "", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        new Conexion().getSt().execute(""
                                + "update caracteristicas "
                                + "set cantidad = cantidad + " + this.sCantidad.getText() + " "
                                + "where Articulo_idArticulo = " + this.articulo_tipo.get(this.sArticulo.getSelectedIndex()).getId() + " "
                                + "and "
                                + "numero = " + (this.sNumero.getSelectedItem().toString()) + "");
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }

            }
        }
        this.sCantidad.setText("");
        Inventario.mthis.consultar();
        if (JOptionPane.showConfirmDialog(this, "¿Desea cerrar esta ventana?") == JOptionPane.OK_OPTION) {
            dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void sCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCantidadActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaMercancia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JComboBox sArticulo;
    public javax.swing.JTextField sCantidad;
    private javax.swing.JLabel sNota;
    public javax.swing.JComboBox sNumero;
    // End of variables declaration//GEN-END:variables

    private void consulta() {
        try {
            this.articulo_tipo = new ArrayList<MCArticuloTipo>();
            this.sArticulo.removeAllItems();
            ResultSet rs = new Conexion().getSt().executeQuery(""
                    + ""
                    + "select idArticulo, modelo, tipo "
                    + "from articulo, tipo "
                    + "where idTipo = Tipo_idTipo");
            while (rs.next()) {
                this.articulo_tipo.add(new MCArticuloTipo(rs.getInt(1), rs.getString(2), rs.getString(3)));
                this.modelo.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3)});
                this.sArticulo.addItem(rs.getString(2));
            }

        } catch (SQLException ex) {

        }

    }

    public void setId(int i) {
        mcc = new MCCaracteristica();
        mode_editor = true;
        try {
            ResultSet rs = new Conexion().getSt().executeQuery(""
                    + "SELECT "
                    + "idCaracteristicas, "
                    + "numero, "
                    + "cantidad, "
                    + "Articulo_idArticulo, "
                    + "(select modelo from articulo where articulo.idArticulo = Articulo_idArticulo limit 1) "
                    + "FROM caracteristicas where idCaracteristicas = " + i);
            while (rs.next()) {
                mcc.setId(i);
                mcc.setNumero(rs.getFloat(2));
                mcc.setCantidad(rs.getInt(3));
                mcc.setIdArticulo(rs.getInt(4));
                mcc.setModelo(rs.getString(5));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.sCantidad.setText(mcc.getCantidad() + "");
        this.sNota.setText("<html><br>"
                + "<font color=\"blue\"><Datos anteriores:</font><br>"
                + "<font color=\"red\">Numero</font>:     " + mcc.getNumero() + "<br>"
                + "<font color=\"red\">Catnidad</font>:   " + mcc.getCantidad() + "<br>"
                + "<font color=\"red\">Articulo</font>:   " + mcc.getModelo() + "<br></html>");

    }
}
